### ISSUE TITLE
Panic while trying to read from second influxdb node while first is down.

### ISSUE THREAD

**Issue by Enton72** [toni-moreno/influxdb-srelay#28]
Hi, i am trying to query second influxdb node while first is down and i got error ([error.txt](https://github.com/toni-moreno/influxdb-srelay/files/4522884/error.txt))
I am using one influxdb-srelay with one syncflux for each influxdb node. 

config for first syncflux - [syncflux1.txt](https://github.com/toni-moreno/influxdb-srelay/files/4522960/syncflux1.txt)
config for second syncflux - [syncflux2.txt](https://github.com/toni-moreno/influxdb-srelay/files/4522961/syncflux2.txt)
config for srelay - [srelay.txt](https://github.com/toni-moreno/influxdb-srelay/files/4522963/srelay.txt)

I would appreciate if you would find the time to assist me with this matter.

**Comment by Enton72** [comment]
I think i have found origin of the problem, but if you could check my solution.

First thing, to avoid "panic" i've added "return" into influxcluster.go in if clause line 433.

Second thing, i've noticed that inside of structure "Cluster" there is a field "queryRouterEndpointAPI", and when declaring a new variable of "Cluster" type, array "queryRouterEndpointAPI" is empty, so because of that i've added "c.queryRouterEndpointAPI = cfg.QueryRouterEndpointAPI" right above for loop in influxcluster.go file line 100.

**Comment by toni-moreno** [comment]
Hello @Enton72  , thank you a lot for your analysis and diagnostic.  Could you please build a Pull Request  to review and merge please?

**Comment by toni-moreno** [comment]
Hello @Enton72  again.  

Could you check if your panic is the same than happened here https://github.com/toni-moreno/influxdb-srelay/issues/25 ? . Could you please also paste a the stack trace panic output?

**Comment by toni-moreno** [comment]
Hello @Enton72 again .
I've recovered a new old issue that seems to be related with this one. https://github.com/toni-moreno/influxdb-srelay/issues/22 . do you agree?

**Comment by Enton-72** [comment]
Hello @toni-moreno.

I am not shure how to build a pull request, it is asking me for public ssh key when i try to push to 
a new branch.

The panic had been caused by the same line _influxcluster.go:436_, but i can't tell you for sure if it is caused same way.

Yes, i agree. He could not find where c.queryRouterEndpointAPI is filled by the cfg config, because it is not filled.

_Stack Trace:_
2020/04/23 08:34:14 http: panic serving 10.10.210.86:2332: runtime error: invalid memory address or nil pointer dereference
goroutine 306 [running]:
net/http.(*conn).serve.func1(0xc00038c000)
/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x867060, 0xc8a110)
/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/toni-moreno/influxdb-srelay/cluster.(*Cluster).handleQuery(0xc0001d0360, 0x975dc0, 0xc0002540e0, 0xc0001a6400, 0xc0001975c0)
/root/go/src/github.com/toni-moreno/influxdb-srelay/cluster/influxcluster.go:436 +0x227
github.com/toni-moreno/influxdb-srelay/cluster.(*Cluster).handleQueryHA(0xc0001d0360, 0x975dc0, 0xc0002540e0, 0xc0001a6400)
/root/go/src/github.com/toni-moreno/influxdb-srelay/cluster/influxcluster.go:405 +0x1b7
github.com/toni-moreno/influxdb-srelay/relay.(*RouteRule).ActionRouteHTTP(0xc000197780, 0x975dc0, 0xc0002540e0, 0xc0001a6400, 0xc0000f9b90, 0x0, 0x0, 0xc0001cc028)
/root/go/src/github.com/toni-moreno/influxdb-srelay/relay/http_route.go:133 +0x500
github.com/toni-moreno/influxdb-srelay/relay.(*HTTPRoute).ProcessRules(0xc0001aa4d0, 0x975dc0, 0xc0002540e0, 0xc0001a6400, 0xc0000f9b90)
/root/go/src/github.com/toni-moreno/influxdb-srelay/relay/http_route.go:628 +0x154
github.com/toni-moreno/influxdb-srelay/relay.(*HTTPEndPoint).ProcessRead(0xc000197740, 0x975dc0, 0xc0002540e0, 0xc0001a6400, 0xc0000f9b90)
/root/go/src/github.com/toni-moreno/influxdb-srelay/relay/http_endpoint.go:76 +0x382
github.com/toni-moreno/influxdb-srelay/relay.(*HTTPEndPoint).ProcessInput(0xc000197740, 0x975dc0, 0xc0002540e0, 0xc0001a6400, 0x3)
/root/go/src/github.com/toni-moreno/influxdb-srelay/relay/http_endpoint.go:129 +0x1a3
github.com/toni-moreno/influxdb-srelay/relay.(*HTTP).processEndpoint(0xc0001d03f0, 0x975dc0, 0xc0002540e0, 0xc0001a6400)
/root/go/src/github.com/toni-moreno/influxdb-srelay/relay/http.go:182 +0x1df
github.com/toni-moreno/influxdb-srelay/relay.(*HTTP).bodyMiddleWare.func1(0xc0001d03f0, 0x975dc0, 0xc0002540e0, 0xc0001a6400)
/root/go/src/github.com/toni-moreno/influxdb-srelay/relay/http_middlewares.go:37 +0x101
github.com/toni-moreno/influxdb-srelay/relay.(*HTTP).queryMiddleWare.func1(0xc0001d03f0, 0x975dc0, 0xc0002540e0, 0xc0001a6400)
/root/go/src/github.com/toni-moreno/influxdb-srelay/relay/http_middlewares.go:57 +0x15c
github.com/toni-moreno/influxdb-srelay/relay.(*HTTP).logMiddleWare.func1(0xc0001d03f0, 0x975dc0, 0xc0002540e0, 0xc0001a6400)
/root/go/src/github.com/toni-moreno/influxdb-srelay/relay/http_middlewares.go:66 +0x9d
github.com/toni-moreno/influxdb-srelay/relay.(*HTTP).rateMiddleware.func1(0xc0001d03f0, 0x975dc0, 0xc0002540e0, 0xc0001a6400)
/root/go/src/github.com/toni-moreno/influxdb-srelay/relay/http_middlewares.go:100 +0x26f
github.com/toni-moreno/influxdb-srelay/relay.(*HTTP).ServeHTTP(0xc0001d03f0, 0x975dc0, 0xc0002540e0, 0xc0001a6300)
/root/go/src/github.com/toni-moreno/influxdb-srelay/relay/http.go:201 +0x174
net/http.serverHandler.ServeHTTP(0xc0001cc4e0, 0x975dc0, 0xc0002540e0, 0xc0001a6300)
/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc00038c000, 0x976d00, 0xc000196500)
/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
/usr/local/go/src/net/http/server.go:2884 +0x2f4
